### ISSUE TITLE
Node.js runtime requirement is not listed

### ISSUE THREAD

**Issue by BanzaiMan** [yarnpkg/website#269]
Due to the dependency on `request`, yarn requires Node.js 4 or later, but this requirement is not explicit in the documents. https://yarnpkg.com/en/docs/install seems like a natural place to put this information, but other places might work as well.

**Comment by Daniel15** [comment]
You do get a message when you run Yarn ("Node version x.xx is not supported, please use Node.js 4.0 or higher"), but I agree that it should be listed on the site too 😄

**Comment by BanzaiMan** [comment]
I don't see that message.

```sh-session
$ nvm use 0.10
Now using node v0.10.48 (npm v2.15.1)
$ yarn

/Users/asari/.nvm/v0.10.48/lib/node_modules/yarn/lib-legacy/constants.js:7
const path = require('path');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/asari/.nvm/v0.10.48/lib/node_modules/yarn/bin/yarn.js:9:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by Daniel15** [comment]
Ahhhh good catch @BanzaiMan! I think it's not even reaching the version check due to the usage of `const` in `constants.js`. I filed an issue here: https://github.com/yarnpkg/yarn/issues/1898

**Comment by Haroenv** [comment]
closed by https://github.com/yarnpkg/yarn/issues/1898
